CREATE TABLE factor
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    type         VARCHAR(255),
    weight_min   DOUBLE PRECISION                        NOT NULL,
    weight_max   DOUBLE PRECISION                        NOT NULL,
    weight_value DOUBLE PRECISION                        NOT NULL,
    session_id   BIGINT,
    CONSTRAINT pk_factor PRIMARY KEY (id)
);